### ISSUE TITLE
Increase upload limit

### ISSUE THREAD

**Issue by stonor** [corbinu/docker-phpmyadmin#1]
Currently the upload limit is 2MB. It would be great to increase this to allow bigger database dumps to be imported. 

The values of
upload_max_filesize
post_max_size 

in /etc/php5/fpm/php.ini needs to be increased to e.g 100M.

The same goes for the client_max_body_size value i Nginx.

**Comment by marmotz** [comment]
+1

**Comment by corbinu** [comment]
Hey sorry Github never alerted me when this issue was first started. I will do an update ASAP thanks.
