### ISSUE TITLE
Allow Creation of DB's and Users

### ISSUE THREAD

**Issue by NerdsvilleCEO** [corbinu/docker-phpmyadmin#14]
Would it be possible for us to modify the SQL and add GRANT CREATE on *.*  GRANT CREATE USER ON *.*, etc etc

**Comment by corbinu** [comment]
No the SQL is for PHPMyAdmins own table access. You are responsible for setting up your MySQL usership. If simply using as it shows in the README you should end up with a root password for the MySQL container and can create whatever users you like with that.
