### ISSUE TITLE
Connection lost when msyql container is restarted

### ISSUE THREAD

**Issue by dmp1ce** [corbinu/docker-phpmyadmin#15]
When the mysql container is restart it is likely going to change it's IP address. If PHPMyAdmin is finding the host from the environment variable then it will not be correct because the environment variable is not updated by docker. The /etc/hosts file is updated by docker however. If you allow this container to be configured with a hosts alias instead relying on the docker link environment variable then when the database IP changes, PHPMyAdmin won't lose connection.

**Comment by corbinu** [comment]
That is a non standard way of configuring docker containers. 

See the official Wordpress Container as an example. https://hub.docker.com/_/wordpress/

There is no reason you should not be able to simply recreate the PHPMyAdmin container after a MySQL restart as no data is persisted inside the container.

**Comment by corbinu** [comment]
If you do what your container's IP address to persist take al look at http://weave.works

**Comment by dmp1ce** [comment]
Why is using the host name non standard? Is there a best practice documented somewhere?

I use docker-compose and when is use `docker-compose stop && docker-compose up` I lose connection to mysql.

Also, I noticed in the documentation that the `/etc/hosts` entries are recommended to be used for linked containers. http://docs.docker.com/userguide/dockerlinks/#important-notes-on-docker-environment-variables

**Comment by corbinu** [comment]
It is non standard as it is not what is used in the official docker containers for example
https://github.com/docker-library/wordpress/blob/3447b0ea9c1eccf1e00feb8e2e70c311690763af/fpm/docker-entrypoint.sh

docker-compose is still in a great deal of flux I suggest you open an issue there for that command not running correctly. You will probably get the best luck if you point out that the official word press container has the same issue.

That appears to be new documentation as of 1.8 and as I said before is not how the offical docker images are currently structured. If there is a breaking change in the linking standard my guess would be that will be enforced in docker 2.0

**Comment by corbinu** [comment]
Also my suggestion you recreate will still work simply use 
`docker-compose rm && docker-compose up`

As long as your docker compose has MySQL set to persist it's data to the host FS you should get the behavior your looking for

**Comment by corbinu** [comment]
If you do not want to persist the data try this
`docker-compose stop && docker-compose rm phpmyadmin && docker-compose up`

**Comment by dmp1ce** [comment]
Thank you for the response. I'm not sure what the bug to docker compose would be. They already have a several bugs about environment variables not updating when containers are recreated and the IP changes.

I guess I'll have to wait and see if the docker team decides on `/etc/hosts` or environment variables for linking containers.

BTW, `docker-compose up --force-recreate phpmyadmin` also gets the job done. That use to be the default in compose but I think they changed it because recreating the container every time takes more time. It is more efficient to just use the old container.
