### ISSUE TITLE
Setting up phpmyadmin/controluser + persistent data

### ISSUE THREAD

**Issue by adamkdean** [corbinu/docker-phpmyadmin#20]
Hi, thanks for this, nice to see phpmyadmin work out of the box (almost) like it should. I had a few extra steps to take though, so just wanted to flag them.

First thing, I create a volume container for the mysql data:

    docker run \
        --name mysql-data \
        --volume /var/lib/mysql \
        busybox

Next up, I start the mysql server, but I pass in the user, password, and database for phpmyadmin:

    docker run \
        --detach \
        --name mysql \
        --volumes-from mysql-data \
        --env MYSQL_ROOT_PASSWORD=**snip** \
        --env MYSQL_USER=pma \
        --env MYSQL_PASSWORD=password \
        --env MYSQL_DATABASE=phpmyadmin \
        --publish 3306 \
        mysql:5.6

Note, the phpmyadmin container has controluser's username password set in `/www/config.inc.php` to `pma` and `password`. You could change that if you liked, but this is localhost only user and personal project so whatever.

Next up, I start your container:

    docker run \
        --detach \
        --link mysql:mysql \
        --name phpmyadmin \
        --publish 8000:80 \
        corbinu/docker-phpmyadmin

And then finally, once I login as my root user, I go to the phpmyadmin database, and run this the script from `/www/sql/create_tables.sql`. It's long, so it's in a gist: https://gist.github.com/adamkdean/b4e99e20db5ba1a652dd.

After this, everything is good, but these were just a few extra steps I _had_ to take to get it running properly.

I found this source to be helpful: http://stackoverflow.com/a/11506495/1138620

**Comment by corbinu** [comment]
Hello,

Thanks for the feedback I believe your issue was two fold. First of all creating the control user and create_tables.sql are run on first run of the container. So they should not be created when starting the mysql container. 

Also you failed to provide $MYSQL_USERNAME  $MYSQL_PASSWORD to the phpmyadmin container to allow the creation of the control user.

**Comment by adamkdean** [comment]
Thanks for the response, corbinu. I wasn't aware that those two variables were required, as per the README: `docker run -d --link phpmyadmin-mysql:mysql -e MYSQL_USERNAME=root --name phpmyadmin -p 80 corbinu/docker-phpmyadmin`, but I'll give it a go with them and see how that goes, maybe submit a PR with a clarified README if you'd like.

Thanks again for your hard work, it's appreciated.
