### ISSUE TITLE
The phpMyAdmin configuration storage has been deactivated.

### ISSUE THREAD

**Issue by JosephLutz** [corbinu/docker-phpmyadmin#6]
'docker logs phpmyadmin' gived the error :
    /usr/local/bin/phpmyadmin-firstrun: line 6: /www/examples/create_tables.sql: No such file or directory

/www/examples/create_tables.sql looks like it should be /www/sql/create_tables.sql

There may be other issues than this. I have not tried to fix it yet.

**Comment by corbinu** [comment]
Thanks looks like the update to 4.4 included a move of the create tables file will fix asap

**Comment by corbinu** [comment]
Go ahead and try it now

**Comment by JosephLutz** [comment]
looks like that did it
Thanks
