### ISSUE TITLE
Add some documentation on Variables

### ISSUE THREAD

**Issue by The-Judge** [corbinu/docker-phpmyadmin#8]
Please, add some documentation of all available / necessary Environment Variables. I cannot find `PMA_SECRET`, `PMA_URI`, … documented anywhere.

**Comment by corbinu** [comment]
Good idea I will try to make sometime in the next few days. If you want your welcome to take a crack a first draft and make a pull request.

**Comment by The-Judge** [comment]
While I'm on vacation and surfing with tethering of my smartphone for the next days, I cannot promise anything, but I will see what I can do ;)

**Comment by corbinu** [comment]
This image is now deprecated
