### ISSUE TITLE
Add a way to skip `phpmyadmin-firstrun`

### ISSUE THREAD

**Issue by The-Judge** [corbinu/docker-phpmyadmin#9]
When one has a PHPMyAdmin database already on his MySQL server, this isn't needed.

**Comment by corbinu** [comment]
So here is my thought on how to go about it
A) Add check if the table exists.
B) Add an environment variable to enable or disable it. 
C) Document that it it can also be called via docker exec after the fact.

**Comment by The-Judge** [comment]
I'd vote for B. When it issues the removal of the `phpmyadmin-firstrun` - file, it may be set on first run only and must not afterwards.

**Comment by corbinu** [comment]
Sorry those were not "choices" but objectives should have made it 1, 2, 3 my bad

**Comment by corbinu** [comment]
This image is now deprecated
